### ISSUE TITLE
"autograd" has no attribute 'grad'

### ISSUE THREAD

**Issue by ypruan** [caogang/wgan-gp#14]
hello,
     when i try to run the 'gan_minist.py',  the problem 
   ```
... ...
gradients = autograd.grad(outputs=disc_interpolates, inputs=interpolates,
AttributeError: 'module' object has no attribute 'grad'"
```
will arise, how should I tackle this?

**Comment by caogang** [comment]
You should use the latest pytorch version, not the release version. You must install pytorch from github source code.
