### ISSUE TITLE
multi-GPU?

### ISSUE THREAD

**Issue by jiujing23333** [caogang/wgan-gp#15]
It seems can not be trained in multi-GPU. When I do so, it report error "Scatter is not differentiable twice".

**Comment by caogang** [comment]
Sorry, I have not test it on multi-GPU. Maybe you can discuss it on the https://discuss.pytorch.org

**Comment by vishwakftw** [comment]
https://discuss.pytorch.org/t/scatter-not-differentiable-twice/6354

I have the same problem too. Thanks!!

**Comment by rafaelvalle** [comment]
Any update on this?

**Comment by caogang** [comment]
You can refer to newest update here. https://discuss.pytorch.org/t/about-doing-double-backward-within-dataparallel/4596

**Comment by rafaelvalle** [comment]
I did. That message if from 5 Jul 2017 and I wonder if there has been any update.
