### ISSUE TITLE
question of the code

### ISSUE THREAD

**Issue by tartarleft** [caogang/wgan-gp#20]
Hi,
what does the 'grad_outputs' in line 131 of gan_cifar10.py stand for ?Should the parameter be interpolates.size() instead of disc_interpolates.size()?

**Comment by caogang** [comment]
No, it should be disc_interpolates.size(). Because `grad_outputs` is not the outputs of gradient. When performing backward procedure, it will multiply the `outputs` and `grad_outputs`.

**Comment by tartarleft** [comment]
thank u

**Comment by nian-liu** [comment]
Hi @caogang  Why don't directly set grad_outputs=None ?
