### ISSUE TITLE
status?

### ISSUE THREAD

**Issue by greaber** [caogang/wgan-gp#5]
I'm trying to implement the improved training algo and am basing my work on your code.  I get the error "AttributeError: 'module' object has no attribute 'grad'".  Is this because I am using the latest pytorch version but not using pytorch master?  I could try to use master, but if it is really true that convnet layers are not yet supported, it is sort of pointless for now(?).

**Comment by caogang** [comment]
Yes, you need to use the latest pytorch master version, not the release version in the http://pytorch.org. And for now, it is true that convnet layers don't support for calculating grad of grad, but it is on progress :)
